const HR_STATUSES=['جديد','تمت المراجعة','مرشح للمقابلة','تمت المقابلة','مقبول','مرفوض','مؤجل'];
const HR_HISTORY_HEADERS=['Timestamp','Candidate_ID','Old_Status','New_Status','Note'];
const HR_SAFE_FIELDS=['Candidate_ID','first_name','father_name','grandfather_name','surname','gender','birth_date','marital_status','primary_phone','secondary_phone','email','address','landmark','education_level','education_institution','graduation_year','currently_employed','current_employer','current_job_title','current_start_date','current_salary','notice_period','reason_for_leaving_current','microsoft_office_level','computer_level','data_entry_level','erp_level','excel_level','english_level','other_technical_skills','applied_position','expected_salary','how_heard_about_job','available_start_date','knows_masat_employee','referral_employee_name','referral_employee_department','referral_relationship','Submission_Date','Submission_Timestamp','Status','HR_Notes'];
function hrEmail_(){return String(Session.getActiveUser().getEmail()||'').toLowerCase();}
function hrAllowed_(){const email=hrEmail_();const allowed=String(PropertiesService.getScriptProperties().getProperty('HR_ALLOWED_EMAILS')||'').toLowerCase().split(',').map(s=>s.trim()).filter(Boolean);return !!email&&allowed.includes(email);}
function requireHr_(){if(!hrAllowed_())throw Error('غير مصرح بالوصول إلى لوحة الموارد البشرية.');}
function initializeHRDashboard(){const props=PropertiesService.getScriptProperties();if(!props.getProperty('HR_ALLOWED_EMAILS'))props.setProperty('HR_ALLOWED_EMAILS',Session.getEffectiveUser().getEmail());ensureHrStorage_();return true;}
function ensureHrStorage_(){const ss=book_(),c=ss.getSheetByName('Candidates');let headers=c.getRange(1,1,1,c.getLastColumn()).getDisplayValues()[0];['Status','HR_Notes'].forEach(h=>{if(!headers.includes(h)){c.getRange(1,headers.length+1).setValue(h);headers.push(h);}});let h=ss.getSheetByName('Candidate_Status_History');if(!h){h=ss.insertSheet('Candidate_Status_History');h.getRange(1,1,1,HR_HISTORY_HEADERS.length).setValues([HR_HISTORY_HEADERS]);h.setFrozenRows(1);}return h;}
function renderHRDashboard_(){if(!hrAllowed_())return HtmlService.createHtmlOutput('<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><style>body{font:16px Tahoma;padding:60px;text-align:center;color:#24333d}</style><h2>غير مصرح بالوصول إلى لوحة الموارد البشرية.</h2></html>').setTitle('HR Dashboard');return HtmlService.createTemplateFromFile('HRDashboard').evaluate().setTitle('ماسة الجود | لوحة الموارد البشرية').addMetaTag('viewport','width=device-width, initial-scale=1');}
function hrValue_(v){return v instanceof Date?v.toISOString():v;}
function safeCandidate_(headers,row){const out={};HR_SAFE_FIELDS.forEach(k=>{const i=headers.indexOf(k);if(i>=0)out[k]=hrValue_(row[i]);});out.full_name=['first_name','father_name','grandfather_name','surname'].map(k=>out[k]).filter(Boolean).join(' ');return out;}
function getHRDashboardData(){requireHr_();ensureHrStorage_();const c=table_('Candidates'),rows=c.sheet.getLastRow()>1?c.sheet.getRange(2,1,c.sheet.getLastRow()-1,c.headers.length).getValues():[];const e=table_('Candidate_Experiences'),eid=e.headers.indexOf('Candidate_ID'),withExp=new Set();if(eid>=0&&e.sheet.getLastRow()>1)e.sheet.getRange(2,eid+1,e.sheet.getLastRow()-1,1).getDisplayValues().forEach(r=>{if(r[0])withExp.add(r[0]);});const candidates=rows.map((r,i)=>{const x=safeCandidate_(c.headers,r);x.has_experience=withExp.has(String(x.Candidate_ID));x.print_url=printUrl_(c.sheet.getRange(i+2,c.headers.indexOf('Print_Token')+1).getDisplayValue());return x;});return {email:hrEmail_(),statuses:HR_STATUSES,candidates};}
function getHRCandidate(candidateId){requireHr_();const c=table_('Candidates'),idCol=c.headers.indexOf('Candidate_ID');if(idCol<0)throw Error('Candidate_ID missing');const found=c.sheet.getRange(2,idCol+1,Math.max(1,c.sheet.getLastRow()-1),1).createTextFinder(candidateId).matchEntireCell(true).findNext();if(!found)throw Error('المرشح غير موجود');const row=c.sheet.getRange(found.getRow(),1,1,c.headers.length).getValues()[0],candidate=safeCandidate_(c.headers,row);candidate.print_url=printUrl_(String(row[c.headers.indexOf('Print_Token')]||''));const e=table_('Candidate_Experiences'),eid=e.headers.indexOf('Candidate_ID'),experiences=[];if(eid>=0&&e.sheet.getLastRow()>1)e.sheet.getRange(2,1,e.sheet.getLastRow()-1,e.headers.length).getValues().forEach(r=>{if(String(r[eid])===candidateId){const x={};['Company','Job_Title','Tasks','Start_Date','End_Date','Leave_Reason','Last_Salary','Reference_Contact','May_Contact_Reference'].forEach(k=>{const i=e.headers.indexOf(k);if(i>=0)x[k]=hrValue_(r[i]);});experiences.push(x);}});const h=ensureHrStorage_(),history=[];if(h.getLastRow()>1)h.getRange(2,1,h.getLastRow()-1,HR_HISTORY_HEADERS.length).getValues().forEach(r=>{if(String(r[1])===candidateId)history.push({Timestamp:hrValue_(r[0]),Old_Status:r[2],New_Status:r[3],Note:r[4]});});return {candidate,experiences,history:history.reverse(),statuses:HR_STATUSES};}
function updateHRCandidate(candidateId,newStatus,note,hrNotes){requireHr_();if(!HR_STATUSES.includes(newStatus))throw Error('حالة غير صالحة');const lock=LockService.getScriptLock();lock.waitLock(30000);try{const c=table_('Candidates'),idCol=c.headers.indexOf('Candidate_ID'),statusCol=c.headers.indexOf('Status'),notesCol=c.headers.indexOf('HR_Notes');const found=c.sheet.getRange(2,idCol+1,Math.max(1,c.sheet.getLastRow()-1),1).createTextFinder(candidateId).matchEntireCell(true).findNext();if(!found)throw Error('المرشح غير موجود');const oldStatus=String(c.sheet.getRange(found.getRow(),statusCol+1).getDisplayValue()||'جديد');if(newStatus!==oldStatus){c.sheet.getRange(found.getRow(),statusCol+1).setValue(newStatus);ensureHrStorage_().appendRow([new Date(),candidateId,oldStatus,newStatus,String(note||'').trim()]);}c.sheet.getRange(found.getRow(),notesCol+1).setValue(String(hrNotes||'').trim());SpreadsheetApp.flush();return getHRCandidate(candidateId);}finally{lock.releaseLock();}}
